"allow-newer": true
"extra-deps":
- "OneTuple-0.4.1.1"
- "QuickCheck-2.14.3"
- "StateVar-1.2.2"
- "aeson-2.1.2.1"
- "assoc-1.1"
- "async-2.2.4"
- "attoparsec-0.14.4"
- "auto-update-0.1.6"
- "base-compat-0.13.0"
- "base-compat-batteries-0.13.0"
- "base-orphans-0.9.0"
- "bifunctors-5.6.1"
- "comonad-5.0.8"
- "contravariant-1.5.5"
- "data-array-byte-0.1.0.1"
- "data-fix-0.3.2"
- "distributive-0.6.2.1"
- "dlist-1.0"
- "either-5.0.2"
- "foldable1-classes-compat-0.1"
- "generically-0.1.1"
- "hashable-1.4.2.0"
- "hostname-1.0"
- "hsc2hs-0.68.9"
- "hsyslog-5.0.2"
- "indexed-traversable-0.1.2.1"
- "indexed-traversable-instances-0.1.1.2"
- "integer-logarithms-1.0.3.1"
- "katip-0.8.7.4"
- "microlens-0.4.13.1"
- "microlens-th-0.4.3.13"
- "monad-control-1.0.3.1"
- "old-locale-1.0.0.7"
- "primitive-0.8.0.0"
- "profunctors-5.6.2"
- "random-1.2.1.1"
- "resourcet-1.3.0"
- "safe-exceptions-0.1.7.3"
- "scientific-0.3.7.0"
- "semialign-1.3"
- "semigroupoids-6.0.0.1"
- "semigroups-0.20"
- "splitmix-0.1.0.4"
- "strict-0.5"
- "string-conv-0.1.2"
- "tagged-0.8.7"
- "text-short-0.1.5"
- "th-abstraction-0.5.0.0"
- "these-1.2"
- "time-compat-1.9.6.1"
- "transformers-base-0.4.6"
- "transformers-compat-0.7.2"
- "unliftio-core-0.2.1.0"
- "unordered-containers-0.2.19.1"
- "uuid-types-1.0.5"
- "vector-0.13.0.0"
- "vector-stream-0.1.0.0"
- "witherable-0.4.2"
flags:
  QuickCheck:
    "old-random": false
    templatehaskell: true
  aeson:
    cffi: false
    "ordered-keymap": true
  assoc:
    tagged: true
  async:
    bench: false
  attoparsec:
    developer: false
  bifunctors:
    tagged: true
  comonad:
    containers: true
    distributive: true
    "indexed-traversable": true
  contravariant:
    semigroups: true
    statevar: true
    tagged: true
  distributive:
    semigroups: true
    tagged: true
  dlist:
    werror: false
  "foldable1-classes-compat":
    tagged: true
  hashable:
    "integer-gmp": true
    "random-initial-seed": false
  hsc2hs:
    "in-ghc-tree": false
  hsyslog:
    "install-examples": false
  "integer-logarithms":
    "check-bounds": false
    "integer-gmp": true
  katip:
    "lib-werror": false
  scientific:
    "bytestring-builder": false
    "integer-simple": false
  semialign:
    semigroupoids: true
  semigroupoids:
    comonad: true
    containers: true
    contravariant: true
    distributive: true
    tagged: true
    "unordered-containers": true
  semigroups:
    binary: true
    bytestring: true
    "bytestring-builder": false
    containers: true
    deepseq: true
    hashable: true
    tagged: true
    "template-haskell": true
    text: true
    transformers: true
    "unordered-containers": true
  splitmix:
    "optimised-mixer": false
  "string-conv":
    "lib-werror": false
  tagged:
    deepseq: true
    transformers: true
  "text-short":
    asserts: false
  "time-compat":
    "old-locale": false
  "transformers-base":
    orphaninstances: true
  "transformers-compat":
    five: false
    "five-three": true
    four: false
    "generic-deriving": true
    mtl: true
    three: false
    two: false
  "unordered-containers":
    debug: false
  vector:
    boundschecks: true
    internalchecks: false
    unsafechecks: false
    wall: false
packages:
- .
resolver: "lts-20.26"
"system-ghc": true
